exports.Menunya = (prefix, pushname, waktoo, totalgroup, totalkontak, totalchat, latensi, runtimenya) => {
return `${botName}

»𝐆𝐫𝐨𝐮𝐩 𝐂𝐡𝐚𝐭𝐬 :  ${totalgroup.length}*
»𝐏𝐫𝐢𝐯𝐚𝐭𝐞 𝐂𝐡𝐚𝐭𝐬 : ${totalkontak.length}*
»𝐓𝐨𝐭𝐚𝐥 𝐂𝐡𝐚𝐭𝐬 : ${totalchat.length}*
»𝐒𝐩𝐞𝐞𝐝 𝐁𝐨𝐭 :  ${latensi.toFixed(4)}*
»𝐑𝐮𝐧𝐭𝐢𝐦𝐞 : ${runtimenya}*

      𝐎𝐖𝐍𝐄𝐑
🪀${prefix}pin*   
🪀${prefix}unpin*
🪀${prefix}bc*
🪀${prefix}tobc*
🪀${prefix}leave*
🪀${prefix}join*
🪀${prefix}self*
🪀${prefix}public*
🪀${prefix}off*
🪀${prefix}on*
🪀${prefix}readall*
🪀${prefix}unreadall*
🪀${prefix}archive*
🪀${prefix}unarchiveall*  
🪀${prefix}return* 
🪀${prefix}status*
🪀${prefix}upswteks*
🪀${prefix}upswimage*
🪀${prefix}upswvideo*
🪀${prefix}antidelete*
🪀${prefix}autorespon*
🪀${prefix}autojoin*
🪀${prefix}anticall*
🪀${prefix}culik*
🪀${prefix}repeat*
🪀${prefix}restart*
🪀${prefix}shutdown*
🪀${prefix}exif*
🪀>/<*
🪀$*
🪀>*
🪀x*

      𝐒𝐄𝐓𝐓𝐈𝐍𝐆
🪀${prefix}setprefix*  
🪀${prefix}setmenu*
🪀${prefix}setthumb*
🪀${prefix}settarget*
🪀${prefix}setfakeimg*
🪀${prefix}setreply*

      𝐏𝐑𝐄𝐌𝐈𝐔𝐌
🪀${prefix}premium add*
🪀${prefix}premium del*
🪀${prefix}listpremium*

      𝐀𝐍𝐎𝐍𝐘𝐌𝐎𝐔𝐒
🪀${prefix}start*
🪀${prefix}keluar*
🪀${prefix}next*

      𝐒𝐓𝐎𝐑𝐀𝐆𝐄
🪀${prefix}sendfile*
🪀${prefix}savefile* 
🪀${prefix}readfile* 
🪀${prefix}downloadfile*

      𝐓𝐎𝐎𝐋𝐒
🪀${prefix}q* 
🪀${prefix}get*  
🪀${prefix}getp*  
🪀${prefix}getbio*
🪀${prefix}getpic* 
🪀${prefix}getname*
🪀${prefix}inspect*
🪀${prefix}searchtext*
🪀${prefix}searchgc*
🪀${prefix}detikvn*
🪀${prefix}detikvideo*
🪀${prefix}tohuruf*
🪀${prefix}fliptext*
🪀${prefix}volume*

      𝐃𝐎𝐖𝐍𝐋𝐎𝐀𝐃   
🪀${prefix}pinterest*
🪀${prefix}youtube*
🪀${prefix}ytsearch*
🪀${prefix}tiktoknowm*
🪀${prefix}playstore*
🪀${prefix}igstalk*
🪀${prefix}play*
🪀${prefix}video*
🪀${prefix}ig*
🪀${prefix}twmp4*
🪀${prefix}twmp3*
🪀${prefix}tiktok*
🪀${prefix}fbmp4*
🪀${prefix}fbmp3*
🪀${prefix}brainly*
🪀${prefix}image*
🪀${prefix}anime*

      𝐌𝐀𝐊𝐄𝐑    
🪀${prefix}dadu*  
🪀${prefix}sticker*
🪀${prefix}swm*
🪀${prefix}take*
🪀${prefix}fdeface*
🪀${prefix}emoji*
🪀${prefix}ytgold*
🪀${prefix}ytsilver*
🪀${prefix}logoa*
🪀${prefix}pornhub*
🪀${prefix}tahta*
🪀${prefix}marvel*
🪀${prefix}wall*
🪀${prefix}foliokiri*
🪀${prefix}foliokanan*
🪀${prefix}nuliskanan*
🪀${prefix}nuliskiri*
🪀${prefix}matrix*
🪀${prefix}googletxt*
🪀${prefix}spiderman*
🪀${prefix}express*
🪀${prefix}dance*
🪀${prefix}blackbird*
🪀${prefix}halloween*
🪀${prefix}vampire*
🪀${prefix}codetxt*
🪀${prefix}text3d*
🪀${prefix}warrior*
🪀${prefix}maker2d2*
🪀${prefix}maker2d3*
🪀${prefix}maker2d4*
🪀${prefix}maker3d*
🪀${prefix}maker3d2*
🪀${prefix}maker3d3*
🪀${prefix}maker3d4*
🪀${prefix}transformer*
🪀${prefix}googletxt*
🪀${prefix}battlefield*
🪀${prefix}coffeecup*
🪀${prefix}coffeecup2*
🪀${prefix}neon*
🪀${prefix}glow*
🪀${prefix}summer*
🪀${prefix}flower*
🪀${prefix}burn*
🪀${prefix}quote*
🪀${prefix}wooden*
🪀${prefix}golden*

      𝐂𝐎𝐍𝐕𝐄𝐑𝐓 
🪀${prefix}toimg*
🪀${prefix}tomp3*
🪀${prefix}tomp4*
🪀${prefix}slow*
🪀${prefix}fast*
🪀${prefix}reverse*
🪀${prefix}tourl*
🪀${prefix}audiotourl*
🪀${prefix}videotourl*
🪀${prefix}stickertourl*

      𝐓𝐀𝐆  
🪀${prefix}tag*
🪀${prefix}tagall*
🪀${prefix}hidetag*
🪀${prefix}kontag*
🪀${prefix}sticktag*
🪀${prefix}totag*

      𝐑𝐀𝐍𝐃𝐎𝐌
🪀${prefix}pantun* 
🪀${prefix}asupan*  
🪀${prefix}storyanime* 
🪀${prefix}komenyt* 
🪀${prefix}quotesyt*     
🪀${prefix}randomukhty*
🪀${prefix}cewethailand*
🪀${prefix}cewevietnam*
🪀${prefix}ceweindo*

      𝐆𝐑𝐎𝐔𝐏
🪀${prefix}add*
🪀${prefix}kick*
🪀${prefix}sider*
🪀${prefix}group*
🪀${prefix}mute*
🪀${prefix}undang*      
🪀${prefix}antilink*
🪀${prefix}antilinkyt*
🪀${prefix}antilinkwame*
🪀${prefix}antiviewonce*
🪀${prefix}welcome*      
🪀${prefix}setname*
🪀${prefix}setdesc*
🪀${prefix}infogrup*
🪀${prefix}revoke*
🪀${prefix}listonline*
🪀${prefix}linkgc*
🪀${prefix}promote*
🪀${prefix}demote*
🪀${prefix}demoteall*
🪀${prefix}demoteall*
🪀${prefix}toviewonc*
🪀${prefix}readviewonce*

      𝐆𝐀𝐌𝐄
🪀${prefix}slot*
🪀${prefix}gelud*
🪀${prefix}tictactoe*
🪀${prefix}suit*
🪀${prefix}resetgame*
🪀${prefix}delsesigelud*

      𝐅𝐔𝐍  
🪀${prefix}hbd*
🪀${prefix}slander*
🪀${prefix}slanderpm*
🪀${prefix}darkjokes*
🪀${prefix}kontak*
🪀${prefix}styletext*
🪀${prefix}phy*
🪀${prefix}fitnah*
🪀${prefix}mining*
🪀${prefix}cekwatak*
🪀${prefix}cekmati*
🪀${prefix}cekbapak*
🪀${prefix}wangy*
🪀${prefix}citacita*
🪀${prefix}toxic*
🪀${prefix}truth*
🪀${prefix}dare*
🪀${prefix}apakah*
🪀${prefix}bisakah*
🪀${prefix}kapankah*
🪀${prefix}rate*
🪀${prefix}jadian*
🪀${prefix}cantik*
🪀${prefix}ganteng*
🪀${prefix}beban*
🪀${prefix}babi*
🪀${prefix}kontol*
🪀${prefix}anjing*
🪀${prefix}alay*
🪀${prefix}cekganteng*
🪀${prefix}cekcantik*

      𝐖𝐈𝐁𝐔
🪀${prefix}cosplay*
🪀${prefix}waifu*
🪀${prefix}loli*
🪀${prefix}husbu*
🪀${prefix}wallml*
🪀${prefix}milf*
🪀${prefix}trapnime*
🪀${prefix}neko*
🪀${prefix}megumin*
🪀${prefix}blowjob*
🪀${prefix}hentai*
🪀${prefix}awoo*
🪀${prefix}bj*
🪀${prefix}eroneko*
🪀${prefix}lesbian*
🪀${prefix}anal*
🪀${prefix}yuri*
🪀${prefix}baka*
🪀${prefix}neko2*
🪀${prefix}wallpaper*
🪀${prefix}pussy*
🪀${prefix}kitsune*
🪀${prefix}keta*
🪀${prefix}neko2*
🪀${prefix}poke*
🪀${prefix}slap*

      𝐁𝐔𝐆
🪀${prefix}pvp*
🪀${prefix}pgp*
🪀${prefix}psp*
🪀${prefix}pcp*
🪀${prefix}plp*
🪀${prefix}buggc*
🪀${prefix}bug*
🪀${prefix}sendbug*
🪀${prefix}bughole*
🪀${prefix}virtex*
🪀${prefix}xbug*
🪀${prefix}command*
🪀${prefix}bugtroli*
🪀${prefix}jadivirus*
🪀${prefix}tovirgam*
🪀${prefix}jadivilip*
🪀${prefix}jadiselayer*
🪀${prefix}jadiselayer2*
🪀${prefix}jadiselayer3*
🪀${prefix}bugholeattack*
🪀${prefix}virtexattack*

      𝐎𝐓𝐇𝐄𝐑𝐒
🪀${prefix}tts* 
🪀${prefix}gci*
🪀${prefix}lacakip* 
🪀${prefix}blocklist*
🪀${prefix}setcmd*
🪀${prefix}delcmd*
🪀${prefix}listcmd*
🪀${prefix}spam*
🪀${prefix}listgroup*
🪀${prefix}size*
🪀${prefix}ping*
🪀${prefix}term*
🪀${prefix}owner*
🪀${prefix}deletepc*

»𝐋𝐢𝐛 𝐁𝐚𝐢𝐥𝐞𝐲𝐬*
»𝐓𝐡𝐚𝐧𝐤𝐬 𝐓𝐨 𝐌𝐲 𝐏𝐚𝐫𝐫𝐞𝐧𝐭𝐬*
»𝐂𝐨𝐩𝐲𝐫𝐢𝐠𝐡𝐭 𝐁𝐲 𝐌𝐚𝐫𝐜𝐞𝐥𝐥シ*`
}
